create table if not exists users
(
    id         bigint generated by default as identity
        primary key,
    active     boolean,
    age        integer,
    email      varchar(255) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null
);

alter table users
    owner to cmas;

